# Generated by Django 3.0.8 on 2020-10-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201018_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('name',)},
        ),
    ]
