# Generated by Django 3.0.8 on 2020-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201019_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
