# Generated by Django 3.0.8 on 2020-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201019_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='gender',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
