# Generated by Django 3.0.8 on 2020-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_subcategory_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_id',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
