# Generated by Django 3.0.8 on 2020-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
