# Generated by Django 3.0.8 on 2020-10-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201020_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ProductItem',
        ),
    ]
