# Generated by Django 3.0.8 on 2020-10-21 20:24

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201021_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=store.models.get_upload_path),
        ),
    ]
