# Generated by Django 3.0.8 on 2020-10-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201021_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
