# Generated by Django 3.0.8 on 2020-10-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201030_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('image_id', models.ImageField(blank=True, default=0, null=True, upload_to='')),
                ('on_sale', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Color')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Size')),
            ],
        ),
    ]
