# Generated by Django 3.0.8 on 2020-10-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201030_0855'),
        ('order', '0003_auto_20201028_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Size'),
        ),
    ]
