# Generated by Django 3.0.8 on 2020-10-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201030_0855'),
        ('order', '0004_shoppingcart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='item',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
